# Generated by Django 3.1.5 on 2021-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
