# Generated by Django 3.1.5 on 2021-01-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210108_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
